function [G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_ind, ...
    p_intended_source_inds, ...
    p_source_model ...
)

    % Chooses the interpolation method based on given source_model and
    % constructs the interpolation matrix G and interpolation (dipole)
    % positions. Errors in case of unknown soure model.

    switch ZefSourceModel.from(p_source_model)

        case ZefSourceModel.Whitney

            [G, dipole_locations] = zef_whitney_interpolation( ...
                p_nodes, ...
                p_tetrahedra, ...
                p_brain_ind, ...
                p_intended_source_inds ...
            );

        case ZefSourceModel.Hdiv

            [G, dipole_locations] = zef_hdiv_interpolation( ...
                p_nodes, ...
                p_tetrahedra, ...
                p_brain_ind, ...
                p_intended_source_inds ...
            );

        otherwise
            error("Unknown source model.");
    end

end
