function barycentra = zef_tetra_barycentra(nodes, tetrahedra)

    % Calculates the barycenters of the given tetrahedra.

    barycentra = 1 / 4 * ( ...
        nodes(tetrahedra(:,1),:) ...
        + ...
        nodes(tetrahedra(:,2),:) ...
        + ...
        nodes(tetrahedra(:,3),:) ...
        + ...
        nodes(tetrahedra(:,4),:) ...
    );
end
